services:
  redis:
    image: redis:latest
    container_name: paytrail_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - "C:/Users/USER/Documents/redis.conf:/etc/redis/redis.conf" #FIXME: USE CORRECT MOUNT POINT
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    mem_limit: 512m

  paytrail:
    image: 545plea/paytrail-backend:latest
    container_name: paytrail
    ports:
      - "3000:3000"
    depends_on:
      - redis
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 10s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    volumes:
      - paytrail_logs:/var/log/paytrail

  grafana-alloy:
    image: grafana/alloy:latest
    container_name: paytrail_grafana_alloy
    ports:
      - "12345:12345"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:12345/-/healthy"]
      interval: 10s
      timeout: 10s
      retries: 5
    command: >
      run
      --server.http.listen-addr=0.0.0.0:12345
      --storage.path=/var/lib/alloy/data
      /etc/alloy/config.alloy
    volumes:
      - paytrail_logs:/var/log/paytrail
      - "C:/Users/USER/Documents/config.alloy:/etc/alloy/config.alloy" #FIXME: USE CORRECT MOUNT POINT
    restart: unless-stopped

volumes:
  redis_data:
  paytrail_logs:
