services:
  redis:
    image: redis:latest
    container_name: paytrail_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - "./redis.conf:/etc/redis/redis.conf"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 10s
      retries: 5
    command: ["redis-server", "/etc/redis/redis.conf"]
    restart: unless-stopped
    mem_limit: 512m

  paytrail:
    image: 545plea/paytrail-backend:latest
    container_name: paytrail
    ports:
      - "3000:3000"
    depends_on:
      - redis
    env_file:
      - .env
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:3000/health",
        ]
      interval: 10s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    volumes:
      - paytrail_logs:/var/log/paytrail

  grafana-alloy:
    image: grafana/alloy:latest
    container_name: paytrail_grafana_alloy
    ports:
      - "12345:12345"
    command: >
      run
      --server.http.listen-addr=0.0.0.0:12345
      --storage.path=/var/lib/alloy/data
      /etc/alloy/config.alloy
    volumes:
      - paytrail_logs:/var/log/paytrail
      - "./config.alloy:/etc/alloy/config.alloy"
      - "./secrets/loki.txt:/var/secrets/loki-password.txt"
      - "./secrets/prometheus.txt:/var/secrets/prometheus-password.txt"
      - "./secrets/loki-username.txt:/var/secrets/loki-username.txt"
      - "./secrets/prometheus-username.txt:/var/secrets/prometheus-username.txt"
    restart: unless-stopped
    mem_limit: 1g

  nginx:
    image: nginx:latest
    container_name: paytrail_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
      - "./certs/paytrail.crt:/etc/nginx/paytrail.crt"
      - "./certs/paytrail.key:/etc/nginx/paytrail.key"
    depends_on:
      - paytrail
    restart: unless-stopped
    mem_limit: 512m

volumes:
  redis_data:
  paytrail_logs:
