name: Continuous Deployment Workflow
on:
  push:
    branches:
      - master
    paths:
      - prisma/**
      - src/**
      - ops/**
      - package*.json
      - Dockerfile

jobs:
  migrations:
    name: "Apply Prisma Migrations"
    environment: production
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Node.js environment
        uses: actions/setup-node@v5.0.0
        with:
          node-version: "24.11.0"
          cache: "npm"

      - name: "Install Dependencies"
        run: npm ci

      - name: "Apply Prisma Migrations"
        id: prisma-migrations
        run: npx prisma migrate deploy
        env:
          DATABASE_URL: ${{secrets.DATABASE_URL}}

  build:
    name: "Build & Push Docker Image"
    needs: migrations
    environment: production
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3.11.1

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/paytrail-backend:latest,${{ secrets.DOCKER_HUB_USERNAME }}/paytrail-backend:${{ github.sha }}
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/paytrail-backend:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/paytrail-backend:buildcache,mode=max

  deploy:
    name: Deploy to Production
    needs: [build]
    environment: production
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Copy the Ops Files to the Server
        uses: Burnett01/rsync-deployments@7.1.0
        with:
          switches: -avr --delete --exclude='.env*'
          path: ./ops/
          remote_path: /home/${{ secrets.REMOTE_USER }}/projects/paytrail/
          remote_host: ${{ secrets.HOSTNAME }}
          remote_user: ${{ secrets.REMOTE_USER }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: "Start the New Paytrail Container"
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.HOSTNAME }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/${{ secrets.REMOTE_USER }}/projects/paytrail

            echo "Pulling new Paytrail Image"

            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/paytrail-backend:latest

            if [ ! $(docker-compose up -d --wait --wait-timeout 120) ]; then
              echo "Container failed to start"

              echo "stopping new running container"
              
              docker-compose stop

              echo "Paytrail logs"

              docker-compose logs paytrail --tail=50

              echo "Redis logs"

              docker-compose logs paytrail_redis --tail=50

              exit 1
            fi

            echo "Removing old images"

            docker image prune -f
