name: Continuous Deployment Workflow

on:
  push:
    branches:
      - master

jobs:
  test:
    name: "Run Tests"
    environment: development
    env:
      DATABASE_URL: ${{secrets.DATABASE_URL}}
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres_123
          POSTGRES_DB: paytrail_postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        name: "Checkout Repository"

      - name: Setup Node.js environment
        uses: actions/setup-node@v5.0.0
        with:
          node-version: "22.12.0"
          cache: "npm"

      - name: "Write .env.test file"
        run: echo "${{ secrets.ENV_TEST_FILE }}" > .env.test

      - name: "Install Dependencies"
        run: npm ci

      - name: "Prisma Migrations"
        run: npx prisma migrate dev

      - name: "Run Tests"
        run: npm run test

  deploy:
    name: "Deploy to Production"
    needs: test
    environment: production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        name: "Checkout repository"

      - name: Setup Node.js environment
        uses: actions/setup-node@v5.0.0
        with:
          node-version: "22.12.0"
          cache: "npm"

      - name: "Install Dependencies"
        run: npm ci

      - name: "Build the Application"
        run: npm run build

      - name: Deploy Build to Server
        uses: Burnett01/rsync-deployments@7.1.0
        with:
          switches: -avr --delete --exclude='.git/' --exclude='node_modules/' --exclude='.env'
          path: ./dist
          remote_path: /var/app
          remote_host: ${{ secrets.HOSTNAME }}
          remote_user: ${{ secrets.REMOTE_USER }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.HOSTNAME }}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /var/app/dist
            pm2 start dist/index.js --name 'paytrail-express-backend' || pm2 restart 'paytrail-express-backend'
            pm2 save
            pm2 startup systemd -u $USER --hp $HOME
            sudo service nginx restart
